version: '3.7'

services:
  nginx:
    hostname: nginx
    image: nginx:1.19.8-alpine
    volumes:
      # configuration
      - ../configurations/nginx/http.conf:/etc/nginx/conf.d/default.conf
      - ../../:/app/
